version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/nginx.Dockerfile
    ports:
      - 8098:80
    volumes:
      - ./camagru:/var/www/camagru
    depends_on:
      - fpm
    links:
      - fpm
  fpm:
    build:
      context: .
      dockerfile: docker/fpm/fpm.Dockerfile
    volumes:
      - ./camagru:/var/www/camagru
    depends_on:
      - mysql
    links:
      - mysql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
  mysql:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: camagru
